const
  IDD_OPT_HISTORYPP    = 207;
  IDD_OPT_HISTORYPP2   = 208;

  ID_APPEARANCE_GROUP  = 100; // "Appearance options" group
  IDC_SHOWEVENTICONS   = 101; // "Show event icons" checkbox
  IDC_RTLDEFAULT       = 102; // "RTL by default" checkbox
  IDC_OPENDETAILS      = 103; // "Open event details by Enter" checkbox
  IDC_SHOWEVENTSCOUNT  = 104; // "Show events count in menu" checkbox
  IDC_SHOWAVATARS      = 105; // "Show avatars" checkbox

  ID_FORMATTING_GROUP  = 200; // "Text formatting options" group
  IDC_BBCODE           = 201; // "Enable BBCodes" checkbox
  IDC_SMILEY           = 202; // "Enable SmileyAdd support" checkbox
  IDC_MATH             = 203; // "Enable MathModule support" checkbox
  IDC_RAWRTF           = 204; // "Enable raw RTF support" checkbox
  IDC_AVATARSHISTORY   = 205; // "Display chanage avatars" checkbox

  ID_MESSAGELOG_GROUP  = 300; // "Message log options" group
  IDC_IEVIEWAPI        = 301; // "Imitate IEView API" checkbox
  IDC_GROUPLOGITEMS    = 302; // "Group messages" checkbox
  IDC_DISABLEBORDER    = 303; // "Disable border" checkbox
  IDC_DISABLESCROLL    = 304; // "Disable scrollbar" checkbox

  ID_HISTORYVIEW_GROUP = 500;// "History view options" group
  IDC_RECENTONTOP      = 501; // "Recent events on top" checkbox
  IDC_GROUPHISTITEMS   = 502; // "Group messages" checkbox

  ID_NEEDOPTIONS_LINK  = 250; // "Visit Wiki page for more options" hyperlink

  ID_NEED_RESTART      = 999; // "Please restart Miranda IM..."

  // second Templates dialog

  IDC_TMPL_COPY        = 100;
  IDC_TMPL_COPYTEXT    = 101;
  IDC_TMPL_QUOTED      = 102;
  IDC_TMPL_QUOTEDTEXT  = 103;
  IDC_TMPL_SELECTION   = 104;

  IDC_TMPL_DATETIME    = 200;

  IDC_TMPL_HELP        = 199;
  IDC_DATE_HELP        = 299;
