{resource constants}
const
  // dialogs
  IDD_ACTION        = 1025;
  IDD_ASK           = 1028;

  // icons
  IDI_NEW           = 1025;
  IDI_UP            = 1026;
  IDI_DOWN          = 1027;
  IDI_DELETE        = 1028;
  IDI_RELOAD        = 1029;
  IDI_TEST          = 1037;
  IDI_EXPORT        = 1038;
  IDI_IMPORT        = 1039;
  IDI_APPLY         = 1044;

  IDC_ACTION_TYPE   = 2005;
  IDC_STAT_ACTION   = 2006;

  IDC_ACTION_LIST   = 2007;
  IDC_ACTION_NEW    = 2008;
  IDC_ACTION_DELETE = 2009;
  IDC_ACTION_UP     = 2010;
  IDC_ACTION_DOWN   = 2011;

  IDC_ACTION_GROUP  = 2012;
  IDC_GROUP_NEW     = 2015;
  IDC_GROUP_RELOAD  = 2016;
  IDC_GROUP_DELETE  = 2017;
  IDC_GROUP_TEST    = 2018;
  IDC_GROUP_UP      = 2019;
  IDC_GROUP_DOWN    = 2020;
  IDC_GROUP_EXPORT  = 2021;
  IDC_GROUP_IMPORT  = 2022;
  IDC_ACTION_HELP   = 2023;

// Question
  IDC_ASK    = 1025;
  IDC_YESALL = 1026;
  IDC_NOALL  = 1027;
  IDC_APPEND = 1028;
